name: pr_auto_assign

on:
  pull_request_target:
    types: [opened]

# プルリクエスト提出時にAssign設定を自動で行なう
# ※念の為タイムアウト設定を3分に指定
jobs:
  assign-author:
    runs-on: ubuntu-latest
    timeout-minutes: 3

    permissions:
      pull-requests: write

    steps:
      - name: PR Auto Assign
        uses: actions/github-script@v6
        with:
          script: |
            const pr = context.payload.pull_request;
            const assignees = [pr.user.login];
            await github.rest.issues.addAssignees({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: pr.number,
              assignees: assignees
            });